// Generated by uRequire v0.7.0-beta.33  template: 'UMD'
(function () {
  
var __isAMD = !!(typeof define === 'function' && define.amd),
    __isNode = (typeof exports === 'object'),
    __isWeb = !__isNode;
(function (factory) {
  if (typeof exports === 'object') {
    var nr = new (require('urequire').NodeRequirer) ('index', module, require, __dirname, '.', undefined);
    module.exports = factory(nr.require, exports, module);
} else if (typeof define === 'function' && define.amd) { define(['require', 'exports', 'module', 'lodash.get'], factory); } else throw new Error('uRequire: Loading UMD module as <script>, without `build.noLoaderUMD`');
}).call(this, function (require, exports, module) {
  

var lodashGet = require("lodash.get");
module.exports = function () {
  var args = Array.prototype.slice.call(arguments);
  var obj = args[0];
  var path = args.slice(1).join(".");
  return lodashGet(obj, path);
};

return module.exports;

});
}).call(this);